debugging CI yml #2

diff --git a/.github/workflows/main-deployment.yml b/.github/workflows/main-deployment.yml
--- a/.github/workflows/main-deployment.yml
+++ b/.github/workflows/main-deployment.yml
@@ -30,12 +30,16 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}
 
-      # Get Azure Container Registry Login Server
+       # Get Azure Container Registry Login Server
       - name: Get ACR Login Server
         id: acr
         run: |
           ACR_LOGIN_SERVER=$(az acr show --name ${{ env.ACR_NAME }} --query "loginServer" --output tsv)
           echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER"
+          if [ -z "$ACR_LOGIN_SERVER" ]; then
+            echo "Failed to get ACR login server URL."
+            exit 1
+          fi
           echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER" >> $GITHUB_ENV
 
       # Get Azure Access Token
@@ -44,6 +48,10 @@ jobs:
         run: |
           TOKEN=$(az account get-access-token --query "accessToken" --output tsv)
           echo "TOKEN=$TOKEN"
+          if [ -z "$TOKEN" ]; then
+            echo "Failed to get Azure access token."
+            exit 1
+          fi
           echo "TOKEN=$TOKEN" >> $GITHUB_ENV
 
       # Login to Azure Container Registry using Access Token
